apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-volume
spec:
  storageClassName: manual-{{ .Values.app }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
