apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeName }}-volume
spec:
  storageClassName: manual-{{ .Values.volumeName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
