apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-volume
  labels:
    type: local
spec:
  storageClassName: manual-letsencrypt
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/khaliqgant/letsencrypt"
