apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-volume
spec:
  storageClassName: manual-letsencrypt
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
