version: "3"
services:
  finance:
    image: finance
    container_name: finance
    volumes:
      - ./config.json:/usr/share/finance-app/config.json
      - data/:/usr/share/finance-app/data/
    ports:
      - 3000:3000
    restart: always
